---
- name: start kibana
  service:
    name: kibana
    state: started

- name: restart kibana
  service:
    name: kibana
    state: restarted

- name: stop kibana
  service:
    name: kibana
    state: stopped
